### ISSUE TITLE
"This version of PaisleyPark only supports Local Only mode"

### ISSUE THREAD

**Issue by Fartagnan** [LeonBlade/PaisleyPark#19]
Hello LeonBlade,

I've recently tried to set up PaisleyPark, however every time i try to load a preset i get the following error message : "This version of PaisleyPark only supports Local Only mode".

Of course, when i tick the "Local Only" checkbox, i am able to load the preset, however obviously other players can't see them so it's not as useful.

I have looked around but was unable to find anyone with the same issue. I'm sure i must be missing something, but i have no idea what it is.

Thank you in advance !

**Comment by LeonBlade** [comment]
One of the patches for FFXIV has removed the ability to place waymarks in combat. Because of this, I have made the tool local only going forward. If you would like to place the waymarks for everyone before battle, you can create a waymark preset in game after loading from Paisley Park and then replacing the waymarks with the in game tool. It's a little messy, but that is the current solution for now.
